# Generated by Django 6.1.2 on 2026-10-08 04:07

import django.utils.timezone
from django.db import migrations, models
from datetime import timedelta


def backfill_remind_at(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    for task in Task.objects.all():
        task.remind_at = task.deadline - timedelta(minutes=task.remind_before_minutes)
        task.save(update_fields=["remind_at"])

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remind_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='task',
            name='remind_before_minutes',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.RunPython(backfill_remind_at,migrations.RunPython.noop),
    ]
